networks:
 expenese:
volumes:
 mysql:
services:
 backend:
  image: backend:1.0.0
  command: sh -c "sleep 10 && node /opt/backend/index.js"
  networks:
   - expenese
  container_name: backend
  depends_on:
  - mysql


mysql:
 image: mysql:1.0.0
 networks:
  - expenese
 container_name: mysql
 volumes:
 - mysql:/var/lib/mysql


frontend:
 image: frontend:1.0.0
 networks:
  - expenese
 container_name: frontend
 ports:
 - 80:80
 depends_on:
 - backendx





